plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.example.icuapk'
    compileSdkVersion = 'android-36.1'

    defaultConfig {
        applicationId 'com.example.icuapk'
        minSdk 24
        targetSdk 30
        versionCode 26
        versionName 'V5-20261010'
    }

    lint {
        disable 'ExpiredTargetSdkVersion'
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.6.0'
}
